import React from 'react';
import LegalLayout from '../components/LegalLayout';

const sections = [
  {
    id: 'acceptance',
    label: '1. Acceptance of Terms',
    content: (
      <p>
        By accessing and using Intrex, you accept and agree to be bound by the terms and provisions of this
        agreement. If you do not agree to these terms, please do not use our service.
      </p>
    ),
  },
  {
    id: 'service-description',
    label: '2. Service Description',
    content: (
      <p>
        Intrex provides AI-powered interview practice and feedback tools. Our platform analyzes your interview
        performance including video, audio, and responses to provide automated feedback and scoring.
      </p>
    ),
  },
  {
    id: 'user-responsibilities',
    label: '3. User Responsibilities',
    content: (
      <>
        <p>Users agree to:</p>
        <ul className="list-disc list-inside ml-4 mt-2 space-y-2">
          <li>Use the service responsibly and ethically</li>
          <li>Provide accurate information during registration</li>
          <li>Not upload inappropriate or offensive content</li>
          <li>Not attempt to manipulate or abuse the AI analysis system</li>
          <li>Keep account credentials secure and confidential</li>
        </ul>
      </>
    ),
  },
  {
    id: 'ai-feedback',
    label: '4. AI-Generated Feedback',
    content: (
      <p>
        Users understand that interview feedback is generated by automated AI systems and may not always be
        perfectly accurate. The feedback should be used as a guide for improvement and not as a definitive
        assessment of interview performance.
      </p>
    ),
  },
  {
    id: 'content-ownership',
    label: '5. Content Ownership',
    content: (
      <p>
        You retain ownership of all content you upload. By uploading content, you grant Intrex a license to
        process, analyze, and store your content for the purpose of providing our services.
      </p>
    ),
  },
  {
    id: 'liability',
    label: '6. Limitation of Liability',
    content: (
      <p>
        Intrex is provided "as is" without warranties of any kind. We are not liable for any damages arising
        from the use of our service, including but not limited to interview outcomes or employment decisions.
      </p>
    ),
  },
  {
    id: 'changes',
    label: '7. Changes to Terms',
    content: (
      <p>
        We reserve the right to modify these terms at any time. Continued use of the service after changes
        constitutes acceptance of the modified terms.
      </p>
    ),
  },
  {
    id: 'contact',
    label: '8. Contact',
    content: (
      <p>For questions about these terms, please contact us through our support channels.</p>
    ),
  },
];

const TermsOfService = () => <LegalLayout title="Terms of Service" sections={sections} />;

export default TermsOfService;
